server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: yu-picture-cloud
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture_cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${MYSQL_PASSWORD:}
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000ms
